#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	printf("0\n");
	rt_entry_t *pos;
	int found = 0, mask = 0;
	rt_entry_t *target;
	printf("1\n");
	list_for_each_entry(pos, (&rtable), list) {
	    if((dst&pos->mask) == (pos->dest&pos->mask)) {
	        found = 1;
	        if(pos->mask > mask) {
	            mask = pos->mask;
	            target = pos;
	        }
	    }
	}
	printf("2\n");
	if(found) {
	    return target;
	}
	return NULL;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	fprintf(stderr, "TODO: send ip packet.\n");
	rt_entry_t *entry_pos;
	int i = 0;
	struct ether_header *eth_hdr = (struct ether_header *)packet;
	struct iphdr *ip_hdr = (struct iphdr *)(packet+sizeof(struct ether_header));
	entry_pos = longest_prefix_match(ntohl(ip_hdr->daddr));
	if(!entry_pos) {
	    icmp_send_packet(packet, len, 3, 0);
	    return;
	}
    u32 gw = entry_pos->gw;
    if(!gw) {
        gw = ntohl(ip_hdr->daddr);
    }
    eth_hdr->ether_type = ntohs(ETH_P_IP);  //?????
    for(i = 0; i < ETH_ALEN; i++) {
        eth_hdr->ether_shost[i] = entry_pos->iface->mac[i];
    }
	iface_send_packet_by_arp(entry_pos->iface, gw, packet, len);
}
